language: csharp
solution: Misc-Beta-Test.sln

install:
- nuget restore Misc-Beta-Test.sln
- nuget install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory test-runner

script:
- msbuild /p:Configuration=Travis Misc-Beta-Test.sln
- cp ./Test-LargeList/bin/x64/Travis/Test-LargeList.dll ./Misc-Beta-Test/bin/x64/Travis
- cp ./Test-PolySerializer/bin/x64/Travis/Test-PolySerializer.dll ./Misc-Beta-Test/bin/x64/Travis
- cp ./Test-SimpleDatabase/bin/x64/Travis/Test-SimpleDatabase.dll ./Misc-Beta-Test/bin/x64/Travis
- cp ./Test-Easly-Controller/bin/x64/Travis/Test-Easly-Controller.dll ./Misc-Beta-Test/bin/x64/Travis
- cp ./Test-Easly-Compiler/bin/x64/Travis/Test-Easly-Compiler.dll ./Misc-Beta-Test/bin/x64/Travis
- cp ./Test-FormattedNumber/bin/x64/Travis/Test-FormattedNumber.dll ./Misc-Beta-Test/bin/x64/Travis

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./Misc-Beta-Test/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master

